SET APP_PACKAGE = 'LUNCH_PLANNER_PACKAGE';
SET APP_DEV_ROLE = 'LUNCH_PLANNER_APP_DEVELOPER';
SET APP_PACKAGE_SCHEMA = CONCAT($APP_PACKAGE, '.PUBLIC');
SET APP_PACKAGE_STAGE = CONCAT($APP_PACKAGE_SCHEMA, '.APPLICATIONCODE');

USE ROLE ACCOUNTADMIN;

-- Ensure ACCOUNTADMIN can create app packages (not default)
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE ACCOUNTADMIN;

-- This role will be given to all developers
CREATE ROLE IF NOT EXISTS IDENTIFIER($APP_DEV_ROLE);
GRANT ROLE IDENTIFIER($APP_DEV_ROLE) TO USER <YOUR_USERNAME>;

-- The Application Package is used to manage the source of the Application. Acts kinda like a repo
CREATE APPLICATION PACKAGE IF NOT EXISTS IDENTIFIER($APP_PACKAGE)
    COMMENT = 'Code repository for native app for blog article'
    DISTRIBUTION = 'INTERNAL';
-- The application code files will be uploaded here
CREATE STAGE IF NOT EXISTS IDENTIFIER($APP_PACKAGE_STAGE)
  DIRECTORY = (ENABLE = true);

-- Grant necessary privileges to LUNCH_PLANNER_APP_DEVELOPER role
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE IDENTIFIER($APP_DEV_ROLE);

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE IDENTIFIER($APP_DEV_ROLE);
GRANT ALL ON APPLICATION PACKAGE IDENTIFIER($APP_PACKAGE) TO ROLE IDENTIFIER($APP_DEV_ROLE);

GRANT USAGE ON SCHEMA IDENTIFIER($APP_PACKAGE_SCHEMA) TO ROLE IDENTIFIER($APP_DEV_ROLE);
GRANT READ ON STAGE IDENTIFIER($APP_PACKAGE_STAGE) TO ROLE IDENTIFIER($APP_DEV_ROLE);
GRANT WRITE ON STAGE IDENTIFIER($APP_PACKAGE_STAGE) TO ROLE IDENTIFIER($APP_DEV_ROLE);

-- Create shared data table in application package
USE APPLICATION PACKAGE IDENTIFIER($APP_PACKAGE);
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS shared_data;
USE SCHEMA shared_data;
CREATE TABLE IF NOT EXISTS ingredients (NAME VARCHAR, OTHER_NAMES VARCHAR);
TRUNCATE TABLE ingredients;
INSERT INTO ingredients VALUES
  ('Milk', ''),
  ('Cheese', ''),
  ('Egg', 'Eggs, Egg Whites, Yolk, Yolks'),
  ('Butter', '');
-- grant usage on the ``ingredients`` table
GRANT USAGE ON SCHEMA shared_data TO SHARE IN APPLICATION PACKAGE IDENTIFIER($APP_PACKAGE);
GRANT SELECT ON TABLE ingredients TO SHARE IN APPLICATION PACKAGE IDENTIFIER($APP_PACKAGE);

-- ===== Code should be uploaded now to the stage ===== --
