SET APP_PACKAGE = 'LUNCH_PLANNER_PACKAGE';
SET APP_DEV_ROLE = 'LUNCH_PLANNER_APP_DEVELOPER';
SET APP_NAME = 'LUNCH_PLANNER_APP';
SET SOURCE_DATABASE = 'lunch_planner_db';

USE ROLE IDENTIFIER($APP_DEV_ROLE);
DROP APPLICATION IF EXISTS IDENTIFIER($APP_NAME);

USE ROLE ACCOUNTADMIN;
DROP APPLICATION PACKAGE IF EXISTS IDENTIFIER($APP_PACKAGE);
DROP ROLE IF EXISTS IDENTIFIER($APP_DEV_ROLE);
DROP INTEGRATION edamam_external_access_integration;
DROP NETWORK RULE edamam_apis_network_rule;
-- Optional: Drop LUNCH_PLAN DB 
-- DROP DATABASE IDENTIFIER($SOURCE_DATABASE);